export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const POSITION_SIDEBAR = 'POSITION_SIDEBAR';
export const TOGGLE_OPEN_SIDEBAR = 'TOGGLE_OPEN_SIDEBAR';
export const CHANGE_ACTIVE_SIDEBAR_ITEM = 'CHANGE_ACTIVE_SIDEBAR_ITEM';
export const TOGGLE_VISIBILITY_SIDEBAR = 'TOGGLE_VISIBILITY_SIDEBAR';

export const DISMISS_ALERT = 'DISMISS_ALERT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_AGENT_IDS_REQUEST = 'FETCH_AGENT_IDS_REQUEST';
export const FETCH_AGENT_IDS_SUCCESS = 'FETCH_AGENT_IDS_SUCCESS';
export const FETCH_AGENT_IDS_FAILURE = 'FETCH_AGENT_IDS_FAILURE';

export const FETCH_AGENT_REQUEST = 'FETCH_AGENT_REQUEST';
export const FETCH_AGENT_SUCCESS = 'FETCH_AGENT_SUCCESS';
export const FETCH_AGENT_FAILURE = 'FETCH_AGENT_FAILURE';
